---
title: "Project in BAN400"
author: "Nina, Stan and Imran (Group 99 )"
date: "29 10 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#add docstring
#use map functions if possible

# Uploading packages that we are going to use (add more if necessary)
library(readxl)           #reading an excel file
library(tidyverse)        #for ggplot2, magrittr pipes, dplyr, etc
library(docstring)
library(priceR)
library(shiny)
```

```{r Make a graph and GIF}

# import the priceR package
library(priceR)

# make the output
output <- historical_exchange_rates("EUR", to = "NOK",
                          start_date = "2018-01-01", end_date = "2020-11-21")


# # libraries needed to create GIF
# library(ggplot2)
# library(tidyverse)
# library(gganimate)
# library(gifski)
# 
# # making the plot
# plot <- output %>%
#   mutate(date = as.Date(date)) %>%
#   ggplot(aes(x = date, y = one_EUR_equivalent_to_x_NOK, group = 1)) +
#   geom_line() +
#   geom_smooth(method = 'loess')+
#   ylab("Price of one EUR in NOK")+
#   xlab("Date")+
#   labs(title = "Exchange rates between EUR and NOK")+
#   theme_classic()+
#   transition_reveal(date)
# 
# 
# # producing the GIF
# mygif <- animate(plot, width=1600, height=800, renderer=gifski_renderer(loop=FALSE))
# 
# # saving the GIF
# anim_save(filename="animation.gif", mygif)


```

```{ui shiny}
#include input and output boxes and report on data quality
library(shiny) # shiny package required to build the app

x <- currencies()

ui <- function(){
  fluidPage(
  #' User interface of the exchange rate converter
  #' 
  #' @description Makes a user choose which two currencies they want to
  #' compare within a chosen time period
  #' 
  #'  @usage .. 
  headerPanel("Silicon valley exchange rate converter"),
  
  sidebarLayout(
    sidebarPanel(selectInput(inputId = "currency1",
                             label = "What is the first currency?",
                             choices = x$code,
                             multiple = FALSE,
                             selectize = TRUE,
                             width = NULL,
                             size = NULL),
                 
                 selectInput(inputId = "currency2", 
                             label = "What is the second currency?",
                             choices = x$code,
                             multiple = FALSE,
                             selectize = TRUE,
                             width = NULL,
                             size = NULL),
                 
                 dateRangeInput(inputId = "dates",
                                label = "What time period do you want to look at?",
                                start = "2020-12-01",
                                end = Sys.Date(),
                                min = "2000-01-01",
                                max = Sys.Date(),
                                format = "dd-mm-yyyy",
                                startview = "decade",
                                weekstart = "1")),
                
                mainPanel(#img(src = "something.png", height = 140, width = 400), #for the gif or something
                          textOutput(outputId = "text_rate"),
                          textOutput(outputId = "text_report"),
                          plotOutput(outputId = "plot"))) 
)
}

?ui #documentation of the function

```

```{server shiny}
#server instructions part of the app
server <- function(input, output) {
  
  #the code that generates each output goes inside the render() function
  #render functions create outputs
  
  output$text_rate <- renderText({
    
    fx_rate <- historical_exchange_rates(input$currency1, to = input$currency2, start_date = Sys.Date(), end_date = Sys.Date())
    
    paste("1", input$currency1, "equals", fx_rate[2], input$currency2)
    
    })
  
  output$text_report <- renderText(print("the user report is whatever"))
  #if the data is current or if the data is not current
#how volatile is the data?
#ask Big Hawk what we're supposed to test???
  
  #all the code to make a plot goes between the braces and is passed on to the renderPlot() function.
  output$plot <- renderPlot({
    
     table <- historical_exchange_rates(input$currency1, to = input$currency2, start_date = input$dates[1], end_date = input$dates[2])
     
    graph_title <- paste("the historical exchange rate of",
                   input$currency1,
                   "/",
                   input$currency2)
    
    table %>%
      mutate(date = as.Date(date)) %>%
      ggplot(aes(x = date, y = table[, 2], group = 1)) +
      geom_line() +
      geom_smooth(method = 'loess')+
      ylab("Currency exchange rate")+
      xlab("Date")+
      labs(title = graph_title)+
      theme_classic()
      #transition_reveal(date)
    #plot(head(table[, 2]) , main = title)
    })

}

```


```{shiny App}
#create the shiny app from the UI and the server parts
shinyApp(ui = ui, server = server)
```

